######################## default configuration ####################
baseURL = "https://editoragatobravo.netlify.com"
languageCode = "pt-BR"
title = "Editora Gato Bravo"
theme = "hargo-theme"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Catálogo"
  URL = "products"
  weight = 1
  
  [[menu.main]]
  name = "Instagram"
  URL = "https://www.instagram.com/editoragatobravo"
  weight = 2
  
  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.main]]
  name = "Contacto"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Catálogo"
  URL = "products"
  weight = 1
  
  [[menu.footer]]
  name = "Instagram"
  URL = "https://www.instagram.com/editoragatobravo"
  weight = 2
  
  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3
  
  [[menu.footer]]
  name = "Termos e Condições"
  URL = "terms-conditions"
  weight = 4
  
  [[menu.footer]]
  name = "Contacto"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logoSite.png"
home = "Início"

# Meta data
description = "Editora Gato Bravo | Transforme as suas ideias em livros"
author = "Themefisher"

# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"

# Google Analitycs
googleAnalitycsID = "Your ID"

# Contact Information
mobile = "+351 308803682"
email = "editoragatobravo@gmail.com"
location = "Lisboa, Portugal | Rio de Janeiro, Brasil"
# copyright
copyright = "| @2019 [Editora Gato Bravo](https://www.editoragatobravo.pt) Todos os direitos reservados |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "images/gatoBravoLogo.png" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = false
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "http://www.fb.com/editoragatobravo"
  
# [[params.social]]
# icon = "ti-twitter-alt"
# link = "#"
  
# [[params.social]]
# icon = "ti-youtube"
# link = "#"
  
  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/editoragatobravo/"
  
# [[params.social]]
#  icon = "ti-pinterest"
# link = "#"

  # Contact Form
  [params.contact]
  formAction = "https://getform.io/f/866fed9f-eb6d-40da-8eed-ad9ccfaaf36c" # contact form works with formspree.io